#Based on template from: https://github.com/ThreeDeeJay/GitHub-Actions-build-templates/blob/main/Windows-MSBuild.yml
name: Build

env:
  GH_TOKEN: ${{github.token}}
  Branch: ${{github.ref_name}}
  Artifacts: build/Release
  Title: ${{github.event.repository.name}}
  Solution: ${{github.event.repository.name}}.sln # .
  Executable: ${{github.event.repository.name}}.exe # *
#  DXSDK_DIR: C:\Program Files (x86)\Microsoft DirectX SDK (June 2010)\
#  VULKAN_VERSION: 1.1.130.0

on:
  push:
    Branches: $Branch
  pull_request:
    Branches: $Branch
  workflow_dispatch:

jobs:
  Build:
    name: ${{matrix.Settings.Name}}-${{matrix.Configuration}}
    runs-on: windows-2022
    strategy:
      matrix:
        Configuration: [Release] #[Release, Debug]
        Settings:
#        - {
#            Name: "Win32",
#            Platform: "Win32",
#            Architecture: "x86",
#            Triplet: "x86-windows"
#          }
        - {
            Name: "Win64",
            Platform: "x64",
            Architecture: "x64",
            Triplet: "x64-windows"
          }
          
    steps:

    - name: Clone repo and submodules
      run: >
        git
        clone https://${{github.repository_owner}}:${{github.token}}@github.com/${{github.repository}}.git
        "${{github.workspace}}"
        --branch ${{env.Branch}}
        --recurse-submodules
        --depth 1

    - name: Clone MathGeoLib
      run: >
        git
        clone https://github.com/juj/MathGeoLib
        "${{github.workspace}}\dependencies\MathGeoLib"
        --depth 1
        --recurse-submodules

    - name: Clone fmt
      run: >
        git
        clone https://github.com/fmtlib/fmt
        "${{github.workspace}}\dependencies\fmt"
        --revision=c4ee726532178e556d923372f29163bd206d7732
        --depth 1
        --recurse-submodules

#    - name: Download Dependencies
#      run: |
#        curl --ssl-revoke-best-effort --create-dirs -L "https://raw.githubusercontent.com/OWNER/REPO/refs/heads/BRANCH/PATH/TO/FILE.EXTENSION" -o "PATH/TO/FILE.EXTENSION"

    - name: Cache vcpkg
      uses: actions/cache@v5
      id: cache_vcpkg
      with:
        path: C:/vcpkg/installed
        key: vcpkg
    - name: vcpkg
      if: steps.cache_vcpkg.outputs.cache-hit != 'true'
      run: |
        vcpkg install glew glfw3 glm fmt tinyobjloader stb --triplet ${{matrix.Settings.Triplet}}
    - name: List vcpkg files
      run: Get-ChildItem -Path "C:\vcpkg" -File -Recurse | Select-Object FullName
